export const GET_USER_DATA_REQUEST ='GET_USER_DATA_REQUEST' 
export const GET_USER_DATA_SUCCESS ='GET_USER_DATA_SUCCESS' 
export const GET_USER_DATA_FAILURE ='GET_USER_DATA_FAILURE'


export const EDIT_BALANCE_REQUEST = "EDIT_BALANCE_REQUEST";
export const EDIT_BALANCE_SUCCESS = "EDIT_BALANCE_SUCCESS";
export const EDIT_BALANCE_FAIL = "EDIT_BALANCE_FAIL";